INSERT INTO PERSONS VALUES(1, 'GUZMAN', 'ANDRES', 'HTML');
INSERT INTO PERSONS VALUES(2, 'ORTIZ', 'MARIA', 'JAVA');
INSERT INTO PERSONS VALUES(3, 'ROGRIGUEZ', 'JESUS', 'PYTHON');
INSERT INTO PERSONS VALUES(4, 'HURTADO', 'CARLOS', 'RUST');
INSERT INTO PERSONS VALUES(5, 'PEREZ', 'ANASTASIA', 'C SHARP');